apiVersion: v1
kind: Service
metadata:
  name: poc-agentic-workflows
  labels:
    app: poc-agentic-workflows
spec:
  type: LoadBalancer
  selector:
    app: poc-agentic-workflows
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
